[package]
name = "smp-fs"
version = "0.1.0"
authors = ["65787978"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { workspace = true, features = ["fullstack"]}
serde = "1.0.159"
simple_logger = "5.0.0"
tracing-wasm = "0.2.1"
tracing = { workspace = true }
tracing-subscriber = "0.3.17"
reqwest = { workspace = true }

[features]
default = []
server = ["dioxus/axum"]
web = ["dioxus/web"]